# Generated by Django 3.2 on 2021-04-30 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonWithThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('residential_address', models.TextField(verbose_name='Адрес проживания')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный телефон')),
                ('vin', models.CharField(max_length=255, verbose_name='Номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование словаря')),
            ],
        ),
        migrations.CreateModel(
            name='StolenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('residential_address', models.TextField(verbose_name='Адрес проживания')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный телефон')),
                ('vin', models.CharField(max_length=255, verbose_name='Номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('check_find', models.BooleanField(default=None, verbose_name='Найден')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stolen', to='search_for_things.thing', verbose_name='Вещь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='PictureStolen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='Картинка')),
                ('file_id_api', models.TextField(verbose_name='file_id from API Telegram')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stolen', to='search_for_things.stolenitem', verbose_name='Связь с лицом')),
            ],
        ),
        migrations.CreateModel(
            name='PicturePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='Картинка')),
                ('file_id_api', models.TextField(verbose_name='file_id from API Telegram')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='search_for_things.personwiththing', verbose_name='Связь с лицом')),
            ],
        ),
        migrations.AddField(
            model_name='personwiththing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_person', to='search_for_things.thing', verbose_name='Вещь'),
        ),
        migrations.AddField(
            model_name='personwiththing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
